#index:
#    path: /
#    controller: App\Controller\DefaultController::index

usuarios:
  path: /usuarios
  controller: App\Controller\UsuarioController::usuarios
  methods: GET|POST

# DELETE no se puede hacer en usuarios porque no se puede borrar en cascada ni tenemos booleano de eliminado

usuario:
  path: /usuario/{id}
  controller: App\Controller\UsuarioController::usuario
  methods: GET|PUT

usuarioEmail:
  path: /loginByEmail
  controller: App\Controller\UsuarioController::usuarioByEmail
  methods: GET

usuarioUsername:
  path: /loginByUsername
  controller: App\Controller\UsuarioController::usuarioByUsername
  methods: GET
  
#seguidoresUsuario:
#  path: /usuario/{id}/seguidos
#  controller: App\Controller\UsuarioController::seguidoresUsuario
#  methods: GET

#seguidorUsuario:
#  path: /usuario/{usuario_id}/sigue/{usuario_seguido_id}
#  controller: App\Controller\UsuarioController::seguidorUsuario
#  methods: POST|DELETE

#configuraciones:
#  path: /configuraciones
#  controller: App\Controller\ConfiguracionController::configuraciones
#  methods: GET

configuracionUsuario:
  path: /usuarios/{usuario_id}/configuracion
  controller: App\Controller\ConfiguracionController::configuracionUsuario
  methods: GET|PUT

podcasts:
  path: /podcasts
  controller: App\Controller\PodcastController::podcasts
  methods: GET

podcast:
  path: /podcast/{id}
  controller: App\Controller\PodcastController::podcast
  methods: GET

usuarioPodcasts:
  path: /usuario/{id}/podcasts
  controller: App\Controller\PodcastController::usuarioPodcasts
  methods: GET

usuarioPodcast:
  path: /usuario/{usuario_id}/podcast/{podcast_id}
  controller: App\Controller\PodcastController::usuarioPodcast
  methods: POST|DELETE

capitulosPodcast:
  path: /podcast/{podcast_id}/capitulos
  controller: App\Controller\CapituloController::capitulosPodcast
  methods: GET

capituloPodcast:
  path: /podcast/{podcast_id}/capitulo/{capitulo_id}
  controller: App\Controller\CapituloController::capituloPodcast
  methods: GET

suscripcionesUsuario:
  path: /usuario/{usuario_id}/suscripciones
  controller: App\Controller\SuscripcionController::suscripcionesUsuario
  methods: GET

suscripcionUsuario:
  path: /usuario/{usuario_id}/suscripcion/{suscripcion_id}
  controller: App\Controller\SuscripcionController::suscripcionUsuario
  methods: GET

playlists:
  path: /playlist
  controller: App\Controller\PlaylistController::playlists
  methods: GET

playlist:
  path: /playlist/{id}
  controller: App\Controller\PlaylistController::playlist
  methods: GET

usuarioPlaylists:
  path: /usuario/{usuario_id}/playlists
  controller: App\Controller\PlaylistController::playlistsUsuario
  methods: GET|POST

usuarioPlaylist:
  path: /usuario/{usuario_id}/playlist/{playlist_id}
  controller: App\Controller\PlaylistController::playlistUsuario
  methods: GET|PUT|DELETE

canciones:
  path: /canciones
  controller: App\Controller\CancionController::canciones
  methods: GET

cancion:
  path: /cancion/{id}
  controller: App\Controller\CancionController::cancion
  methods: GET

cancionesPlaylist:
  path: /playlist/{playlist_id}/canciones
  controller: App\Controller\CancionController::cancionesPlaylist
  methods: GET

cancionPlaylist:
  path: /playlist/{playlist_id}/cancion/{cancion_id}
  controller: App\Controller\CancionController::cancionPlaylist
  methods: POST|DELETE

artistas:
  path: /artistas
  controller: App\Controller\ArtistaController::artistas
  methods: GET

artistaAlbums:
  path: /artista/{artista_id}/albums
  controller: App\Controller\ArtistaController::artistaAlbums
  methods: GET

artistaAlbum:
  path: /artista/{artista_id}/album/{album_id}
  controller: App\Controller\ArtistaController::artistaAlbum
  methods: GET

albums:
  path: /albums
  controller: App\Controller\AlbumController::albums
  methods: GET

album:
  path: /album/{id}
  controller: App\Controller\AlbumController::album
  methods: GET

albumCanciones:
  path: /album/{album_id}/canciones
  controller: App\Controller\AlbumController::albumCanciones
  methods: GET

calidades:
  path: /calidades
  controller: App\Controller\CalidadController::calidades
  methods: GET

Idiomas:
  path: /idiomas
  controller: App\Controller\IdiomaController::idiomas
  methods: GET

#tiposDescargas:
#  path: /tipos-descargas
#  controller: App\Controller\TipoDescargaController::tiposDescargas
#  methods: GET